-- MySQL Script generated by MySQL Workbench
-- Thu Sep 23 13:49:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco_cnae
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_cnae
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_cnae` DEFAULT CHARACTER SET utf8 ;
USE `banco_cnae` ;

-- -----------------------------------------------------
-- Table `agrupamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrupamento` (
  `agrupamento_id` INT NOT NULL AUTO_INCREMENT,
  `agrupamento_codigo` VARCHAR(20) NOT NULL,
  `agrupamento_descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`agrupamento_id`),
  UNIQUE INDEX `agrupamento_id_UNIQUE` (`agrupamento_id` ASC) ,
  UNIQUE INDEX `agrupamento_codigo_UNIQUE` (`agrupamento_codigo` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnae`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnae` (
  `cnae_id` INT NOT NULL AUTO_INCREMENT,
  `cnae_codigo` VARCHAR(20) NOT NULL,
  `cnae_descricao` VARCHAR(200) NOT NULL,
  `fk_agrupamento_id` INT NOT NULL,
  PRIMARY KEY (`cnae_id`),
  UNIQUE INDEX `cnae_id_UNIQUE` (`cnae_id` ASC) ,
  UNIQUE INDEX `cnae_codigo_UNIQUE` (`cnae_codigo` ASC) ,
  INDEX `fk_cnae_agrupamento_idx` (`fk_agrupamento_id` ASC) ,
  CONSTRAINT `fk_cnae_agrupamento`
    FOREIGN KEY (`fk_agrupamento_id`)
    REFERENCES `agrupamento` (`agrupamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grau_de_risco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grau_de_risco` (
  `grau_de_risco_id` INT NOT NULL AUTO_INCREMENT,
  `grau_de_risco_codigo` VARCHAR(20) NOT NULL,
  `grau_de_risco_descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`grau_de_risco_id`),
  UNIQUE INDEX `grau_de_risco_codigo_UNIQUE` (`grau_de_risco_codigo` ASC) ,
  UNIQUE INDEX `grau_de_risco_id_UNIQUE` (`grau_de_risco_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `documentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `documentacao` (
  `documentacao_id` INT NOT NULL AUTO_INCREMENT,
  `documentacao_codigo` VARCHAR(20) NOT NULL,
  `documentacao_descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`documentacao_id`),
  UNIQUE INDEX `documentacao_id_UNIQUE` (`documentacao_id` ASC) ,
  UNIQUE INDEX `documentacao_codigo_UNIQUE` (`documentacao_codigo` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnae_e_grau_de_risco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnae_e_grau_de_risco` (
  `cnae_e_grau_de_risco_id` INT NOT NULL AUTO_INCREMENT,
  `fk_cnae_id` INT NOT NULL,
  `fk_grau_de_risco_id` INT NOT NULL,
  PRIMARY KEY (`cnae_e_grau_de_risco_id`),
  UNIQUE INDEX `cnae_e_grau_de_risco_id_UNIQUE` (`cnae_e_grau_de_risco_id` ASC) ,
  INDEX `fk_cnae_e_grau_de_risco_cnae1_idx` (`fk_cnae_id` ASC) ,
  INDEX `fk_cnae_e_grau_de_risco_grau_de_risco1_idx` (`fk_grau_de_risco_id` ASC) ,
  CONSTRAINT `fk_cnae_e_grau_de_risco_cnae1`
    FOREIGN KEY (`fk_cnae_id`)
    REFERENCES `cnae` (`cnae_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cnae_e_grau_de_risco_grau_de_risco1`
    FOREIGN KEY (`fk_grau_de_risco_id`)
    REFERENCES `grau_de_risco` (`grau_de_risco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnae_e_documentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnae_e_documentacao` (
  `cnae_e_documentacao_id` INT NOT NULL AUTO_INCREMENT,
  `fk_cnae_id` INT NOT NULL,
  `previa_fk_documentacao_id` INT NULL,
  `inicial_fk_documentacao_id` INT NULL,
  PRIMARY KEY (`cnae_e_documentacao_id`),
  UNIQUE INDEX `cnae_e_documentacao_id_UNIQUE` (`cnae_e_documentacao_id` ASC) ,
  INDEX `fk_cnae_e_documentacao_cnae1_idx` (`fk_cnae_id` ASC) ,
  INDEX `fk_cnae_e_documentacao_documentacao1_idx` (`previa_fk_documentacao_id` ASC) ,
  INDEX `fk_cnae_e_documentacao_documentacao2_idx` (`inicial_fk_documentacao_id` ASC) ,
  CONSTRAINT `fk_cnae_e_documentacao_cnae1`
    FOREIGN KEY (`fk_cnae_id`)
    REFERENCES `cnae` (`cnae_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cnae_e_documentacao_documentacao1`
    FOREIGN KEY (`previa_fk_documentacao_id`)
    REFERENCES `documentacao` (`documentacao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cnae_e_documentacao_documentacao2`
    FOREIGN KEY (`inicial_fk_documentacao_id`)
    REFERENCES `documentacao` (`documentacao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
